version: '2'
services:
    try1-app:
        image: try1
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://try1-postgresql:5432/try1
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    try1-postgresql:
        extends:
            file: postgresql.yml
            service: try1-postgresql
