version: '2'
services:
    try1-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/try1/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=try1
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
